### ISSUE TITLE
+1 for the fun README!

### ISSUE THREAD

**Issue by dandv** [leeoniya/preCode.js#1]
> Fuck this!

and

> sucks to your old browser, Piggy!

**Comment by dandv** [comment]
Learned about this from https://github.com/LeaVerou/prism/issues/455#issuecomment-68977283. Awesome stuff.

**Comment by leeoniya** [comment]
considering the effort it takes to write docs/demos/tests for my other more involved repos. this one was destined to be "Eloquent in its brevity" :P

EDIT: though i can never achieve the perfection of http://www.wtfpl.net/about/
