### ISSUE TITLE
First line indented

### ISSUE THREAD

**Issue by sebastiansulinski** [leeoniya/preCode.js#3]
I might be doing something wrong, but the output I get for the following, indents the Doctype line (see the attached image).
![screen shot 2015-10-29 at 16 35 18](https://cloud.githubusercontent.com/assets/2211203/10825028/19579200-7e5b-11e5-9a06-9b74595c7aac.png)

```
<pre class="language-markup">
    <code>
        &lt;!DOCTYPE html&gt;
        &lt;html&gt;
        &lt;head&gt;
        &lt;meta charset="utf-8"&gt;
        &lt;title&gt;Loading / Processing Button&lt;/title&gt;
        &lt;link
            rel="stylesheet"
            type="text/css"
            href="./css/core.css"
            &gt;
        &lt;/head&gt;
        &lt;body&gt;

        &lt;/body&gt;
        &lt;/html&gt;
    </code>
</pre>
```

**Comment by leeoniya** [comment]
the space you're seeing is the whitespace between your opening `<pre>` and `<code>` tags, which this lib doesn't touch. it would add more complexity to handle this, so i prefer to keep it out.

if you write it like this, it should work ok:

``` html
    <pre><code>
        ...
    </code></pre>
```

plus you get to save 1 indentation level :)

**Comment by sebastiansulinski** [comment]
Sorry - it was a different code that was causing it.
